version: '3'

services:
  jenkins:
    image: jenkinsci/blueocean
    environment:
      - DOCKER_SOCKET=/var/run/docker.sock

    ports:
      - 8080:8080

    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
